// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fselect
Rcpp::List fselect(const arma::mat& x, const arma::colvec& y, int nvmax, int ncov);
RcppExport SEXP _varselect_fselect(SEXP xSEXP, SEXP ySEXP, SEXP nvmaxSEXP, SEXP ncovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nvmax(nvmaxSEXP);
    Rcpp::traits::input_parameter< int >::type ncov(ncovSEXP);
    rcpp_result_gen = Rcpp::wrap(fselect(x, y, nvmax, ncov));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_varselect_fselect", (DL_FUNC) &_varselect_fselect, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_varselect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
